language: python
install:
  - pip install -r requirements.txt
script:
  - python -m pytest -sv &
  - while [ -e /proc/$! ]; do SECONDS=0; if [ "$SECONDS" -gt 570 ]; then  echo -n '.'; SECONDS=0; fi; sleep 30; done

