language: python
install:
  - pip install -r requirements.txt
script:
  - python -m pytest -sv &
  - |
    SECONDS=0
    while [ -e /proc/$! ]; do
      if [ "$SECONDS" -gt "570" ]; then
        echo -n '.'
        SECONDS=0
      fi
      sleep 10
    done

